#!/usr/bin/env python3
import json, time, urllib.request
import os
from pathlib import Path

PROFILE_DIR = Path(os.environ.get('HERMES_PROFILE_DIR') or os.environ.get('HERMES_HOME') or (Path.home() / '.hermes'))
BASE = Path(os.environ.get('DIGITAL_BRAIN_99_TASK_DIR') or (PROFILE_DIR / 'tasks' / 'digital-brain-99'))
OUT=BASE/'reports'/f"webui-dogfood-{time.strftime('%Y%m%d_%H%M%S')}"
OUT.mkdir(parents=True, exist_ok=True)
report={'url':'http://127.0.0.1:8233/review','public_url':'https://mg.bz9.me/','screenshots':{},'console':[],'errors':[],'checks':{},'findings':[]}
cred_path=BASE/'dogfood-login.json'
cred=None
if cred_path.exists():
    try:
        cred=json.loads(cred_path.read_text())
        report['checks']['dogfood_login_available']=True
    except Exception as e:
        report['checks']['dogfood_login_available']=False
        report['findings'].append({'severity':'P1','area':'dogfood_setup','title':'Dogfood login credential file is unreadable','detail':repr(e)})
else:
    report['checks']['dogfood_login_available']=False
    report['findings'].append({'severity':'P1','area':'dogfood_setup','title':'Dogfood login credentials missing; authenticated WebUI flow not covered','detail':str(cred_path)})

def fetch_json(url):
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            return {'ok': True, 'status': r.status, 'json': json.loads(r.read().decode('utf-8','replace'))}
    except Exception as e:
        return {'ok': False, 'error': repr(e)}

# API evidence is available even without UI login.
for name,url in {
    'health':'http://127.0.0.1:8233/health',
    'proposal_inbox':'http://127.0.0.1:8233/api/proposal-review/inbox?status=pending&limit=5',
    'review_groups':'http://127.0.0.1:8233/api/review/groups',
    'namespaces':'http://127.0.0.1:8233/api/browse/namespaces',
}.items():
    report['checks'][f'api_{name}']=fetch_json(url)

try:
    from playwright.sync_api import sync_playwright
except Exception as e:
    report['errors'].append({'stage':'import_playwright','error':repr(e)})
    (OUT/'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2))
    print(OUT/'report.json')
    raise SystemExit(2)

with sync_playwright() as p:
    try:
        browser=p.chromium.launch(headless=True)
    except Exception as e:
        report['errors'].append({'stage':'browser_launch','error':repr(e)})
        report['findings'].append({'severity':'P1','area':'dogfood_infra','title':'Playwright browser executable unavailable; authenticated visual QA degraded','detail':repr(e)[:800]})
        browser=None
    if browser is not None:
        page=browser.new_page(viewport={'width':1440,'height':1000}, device_scale_factor=1)
        page.on('console', lambda msg: report['console'].append({'type':msg.type,'text':msg.text[:500]}))
        page.on('pageerror', lambda exc: report['errors'].append({'stage':'pageerror','error':str(exc)[:1000]}))
        page.goto(report['url'], wait_until='networkidle', timeout=30000)
        report['screenshots']['login']=str(OUT/'01-login.png')
        page.screenshot(path=report['screenshots']['login'], full_page=True)
        body=page.locator('body').inner_text(timeout=10000)
        body_lower=body.lower()
        report['checks']['login_body_text_len']=len(body)
        report['checks']['login_has_memory_graph']='memory graph' in body_lower
        report['checks']['login_has_sign_in']='sign in' in body_lower or '登录' in body
        report['checks']['body_background']=page.evaluate("getComputedStyle(document.body).backgroundColor")
        report['checks']['font_family']=page.evaluate("getComputedStyle(document.body).fontFamily")
        report['checks']['button_count']=page.locator('button').count()
        report['checks']['link_count']=page.locator('a').count()
        generic_terms=['Neural Core','fragment','Integration failed','Mass integration','Generated by','AI-powered']
        report['checks']['generic_aiish_terms_on_visible_surface']=[term for term in generic_terms if term.lower() in body_lower]
        if report['checks']['generic_aiish_terms_on_visible_surface']:
            report['findings'].append({'severity':'P1','area':'copywriting','title':'AI-ish/generic copy visible on current surface','detail':report['checks']['generic_aiish_terms_on_visible_surface']})
        if len(body.strip()) < 80:
            report['findings'].append({'severity':'P2','area':'brand_story','title':'Login surface is very sparse; lacks memory-review product narrative','detail':len(body.strip())})

        if cred:
            page.fill('input[placeholder="Username"]', cred['username'])
            page.fill('input[placeholder="Password"]', cred['password'])
            page.click('button:has-text("Sign In")')
            page.wait_for_load_state('networkidle', timeout=30000)
            page.wait_for_timeout(1000)
            report['checks']['authenticated_flow_skipped']=False
            report['checks']['after_login_url']=page.url
            body=page.locator('body').inner_text(timeout=10000)
            body_lower=body.lower()
            report['checks']['body_text_len']=len(body)
            report['checks']['has_review_nav']='review' in body_lower or '审核' in body
            candidate_terms = ('candidates', '候选', 'proposal', 'quarantine', '隔离', 'quarantined', 'release candidates', 'source material')
            report['checks']['has_candidates']=any(term in body_lower for term in candidate_terms[:1] + candidate_terms[2:]) or any(term in body for term in candidate_terms[1:2])
            report['checks']['has_memory_graph']='memory graph' in body_lower or '记忆图谱' in body
            report['checks']['has_settings']='settings' in body_lower or '设置' in body
            report['screenshots']['review']=str(OUT/'02-review.png')
            page.screenshot(path=report['screenshots']['review'], full_page=True)
            try:
                candidates=page.locator('text=/Candidates|候选|Proposals|Quarantine|隔离|Release candidates|Source material/i').first
                if candidates.count():
                    candidates.click(timeout=5000)
                    page.wait_for_timeout(800)
                    report['checks']['candidate_click_ok']=True
                    report['screenshots']['candidates']=str(OUT/'03-candidates.png')
                    page.screenshot(path=report['screenshots']['candidates'], full_page=True)
                else:
                    report['checks']['candidate_click_ok']=False
                    report['findings'].append({'severity':'P1','area':'ux','title':'Candidates tab not discoverable by text search'})
            except Exception as e:
                report['checks']['candidate_click_ok']=False
                report['findings'].append({'severity':'P1','area':'ux','title':'Candidates interaction failed','detail':repr(e)})
            page.set_viewport_size({'width':390,'height':844})
            page.wait_for_timeout(500)
            report['screenshots']['mobile_review']=str(OUT/'04-mobile-review.png')
            page.screenshot(path=report['screenshots']['mobile_review'], full_page=True)
            mobile_text=page.locator('body').inner_text(timeout=5000)
            report['checks']['mobile_body_text_len']=len(mobile_text)
            if not report['checks'].get('has_candidates'):
                report['findings'].append({'severity':'P1','area':'feature_discoverability','title':'Candidates queue not visible/discoverable after login'})
            if report['checks']['mobile_body_text_len'] < 100:
                report['findings'].append({'severity':'P1','area':'responsive','title':'Mobile viewport may not render useful content','detail':report['checks']['mobile_body_text_len']})
        else:
            report['checks']['authenticated_flow_skipped']=True
            # Public mobile login screenshot still catches responsive/brand regressions.
            page.set_viewport_size({'width':390,'height':844})
            page.wait_for_timeout(500)
            report['screenshots']['mobile_login']=str(OUT/'02-mobile-login.png')
            page.screenshot(path=report['screenshots']['mobile_login'], full_page=True)
            mobile_text=page.locator('body').inner_text(timeout=5000)
            report['checks']['mobile_body_text_len']=len(mobile_text)
        severe=[c for c in report['console'] if c.get('type') in ('error','warning')]
        report['checks']['console_error_warning_count']=len(severe)
        if severe:
            report['findings'].append({'severity':'P1','area':'console','title':'Console warnings/errors present','detail':severe[:5]})
        browser.close()

score=6.5
if report['checks'].get('console_error_warning_count',0)==0: score+=0.75
if report['checks'].get('api_proposal_inbox',{}).get('ok'): score+=0.75
if report['checks'].get('dogfood_login_available'): score+=0.75
if report['checks'].get('candidate_click_ok'): score+=0.75
if report['checks'].get('mobile_body_text_len',0)>80: score+=0.5
if not report['checks'].get('generic_aiish_terms_on_visible_surface'): score+=0.5
report['checks']['deterministic_ui_smoke_score_out_of_10']=round(min(score,10),2)

md=OUT/'report.md'
lines=['# Memory Graph WebUI Dogfood Visual Smoke','',f"URL: {report['url']}",f"Public URL: {report['public_url']}",'','## Checks']
for k,v in report['checks'].items():
    compact=json.dumps(v, ensure_ascii=False)[:700] if isinstance(v,(dict,list)) else str(v)
    lines.append(f'- {k}: `{compact}`')
lines += ['','## Screenshots']
for k,v in report['screenshots'].items(): lines.append(f'- {k}: {v}')
lines += ['','## Findings']
if report['findings']:
    for f in report['findings']: lines.append(f"- [{f['severity']}] {f['area']}: {f['title']} {f.get('detail','')}")
else:
    lines.append('- No deterministic P1 findings in this smoke; human visual polish review still required.')
md.write_text('\n'.join(lines)+'\n', encoding='utf-8')
(OUT/'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
print(md)
# Nonzero only if infra/browser failed, not for expected missing login P1.
raise SystemExit(2 if report['errors'] else 0)
